version: "2.2"
services:
    ui:
      build:
        context: ./ui
      ports:
        - "80:80"
        - "443:443"
      restart: always

    server:
      build:
        context: ./server
      restart: always